apiVersion: v1
kind: ConfigMap
metadata:
  name: smartlogix-config
  namespace: smartlogix
data:
  JWT_EXPIRATION: "3600000"
  STOCK_ALERT_THRESHOLD: "10"

  NEON_AUTH_URL: "jdbc:postgresql://postgres-db:5432/smartlogix_local"
  NEON_INVENTARIO_URL: "jdbc:postgresql://postgres-db:5432/smartlogix_local"
  NEON_PEDIDOS_URL: "jdbc:postgresql://postgres-db:5432/smartlogix_local"
  NEON_ENVIOS_URL: "jdbc:postgresql://postgres-db:5432/smartlogix_local"

  CONFIG_VERSION: "v1"
